### ISSUE TITLE
Airpods Max Compatibility Issue

### ISSUE THREAD

**Issue by maniacx** [maniacx/Bluetooth-Battery-Meter#85]
Airpods Max Compatibility.

> @maniacx 
> 
> Thanks for the quick answer!
> 
> Did all of that: disabled ext, forgot device & unpaired, watched logs, enabled ext and re-paired. 
> Same result as the issue before, nothing on syslog; Here's the service.log:
> 
>

**Comment by maniacx** [comment]
@GovanifY

My battery parser was checking only packet length for Multiple batteries and not single battery devices such as Airpods Max.

I have pushed an update on Github.
Install and test it please.

Let me know if the UI displays now.
If it does, test other features too.

And if need to add any other missing features. let me know. We can discuss and work on it.

Thanks for reporting this.

**Comment by GovanifY** [comment]
Hey,

Just tested it, everything seems to work well, both for the battery reporting and ANC toggles

<img width="329" height="422" alt="Image" src="https://github.com/user-attachments/assets/899bb3a6-0623-4ff6-8ae7-9c7a7db99b39" />

Thanks a lot!

**Comment by GovanifY** [comment]
Actually, small issue remaining: "Pause when device is not worn" does not seem to be working

EDIT: seems to work after a gnome-shell restart

**Comment by maniacx** [comment]
Thanks. I will release this as an update for this fix now on Gnome-extension.


> Actually, small issue remaining: "Pause when device is not worn" does not seem to be working
> 
> EDIT: seems to work after a gnome-shell restart

I will take a deeper look at this later next week, when I get the time.

If the above happens again, immediately run and post it.
```
tail -f /tmp/bluetooth_battery_meter/service.log
```
and
```
journalctl -f -o cat /usr/bin/gnome-shell
```

and post it.
